enhance developer docu (add sections describing add/modify/delete translations)
ioBrokerTranslator/doc pull request #7
Opened 2023-01-07 18:11 UTC by mcm1957

Add sections describing mentainence steps to add / modify / delete translations for developers

2023-01-07 18:14 UTC, mcm1957 commented
readme.md
add sections describing howto add / modify / delete a translation

admin.md
add plugin "Cleanup translation files"

2023-04-24 18:48 UTC, mcm1957 commented
@UncleSamSwiss 

Hi, könntest du wenn du Zeit und Lust hast den PR mal überfliegen und mergen oder m ir Bescheid geben was geändert werden sollte?

2023-04-25 03:45 UTC, UncleSamSwiss requested changes
Thanks a lot for the good additions to the texts. There is only one point where I disagree.

2023-04-25 03:45 UTC, UncleSamSwiss commented on translate.md
I disagree with that: the dash character is only used seldom in the English language. We may write "IP Address" as casing is dependent on the context, but I haven't seen "IP-Address" in English text. Ref: https://en.wikipedia.org/wiki/IP_address

2023-04-25 06:09 UTC, mcm1957 commented on translate.md
I reverted this change.
IP address stays unchanged

2023-04-25 06:10 UTC, mcm1957 commented
IP-Address changed back to IP address

2023-04-25 19:25 UTC, UncleSamSwiss approved these changes

2023-04-25 19:26 UTC, merged